# 开发环境配置文件备份
jwt:
  header: Authorization   #http请求头所需要的字段
  secret: lemur_boot        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

spring:
  http:
    converters:
      preferred-json-mapper: fastjson
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  datasource:
    url: jdbc:mysql://db.afterturn.cn:3308/windbell?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: windbell
    password: windbell
    filters: wall,mergeStat
  redis:
    host: dev.cloud.afterturn.cn
    port: 16379
    password: 94456456421321&&&Gdsfs
    database: 2

mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  typeAliasesPackage: cn.afterturn.boot.**.model
  global-config:
    id-type: id_worker  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
  dbConfig:
    field-strategy: not_empty

j2cache:
  open-spring-cache: true
  config-location: j2cache-dev.properties

info:
  owner: Lemur
  version: 1.0
  app:
    name: lemur-admin
    version: 1.0
    description: 管理平台
    spring-boot-version: 2.0.6