jwt:
  header: Authorization   #http请求头所需要的字段
  secret: lemur_boot        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

spring:
  redis:
    host: localhost
    port: 16379
    password: 94456456421321&&&Gdsfs
    database: 4
  cloud:
    gateway:
      routes:
        - id: admin
          uri: http://localhost:9001
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: loan
          uri: http://localhost:9003
          predicates:
            - Path=/loan/**
          filters:
            - StripPrefix=1
        - id: paas
          uri: http://localhost:9002
          predicates:
            - Path=/paas/**
          filters:
            - StripPrefix=1
